
gatesrv:
	cd ../gatesrv;make tolua;make
	rm -rf bin/gatesrv
	ln -s bin/gatesrv ../gatesrv/gatesrv
	cd gatesrv1;./gatesrv

clean:
	cd ../gatesrv;make clean

nodesrv:
	cd ../../../src/engine;make clean;make

