

gatesrv:
	bin/gatesrv gatesrv1

gamesrv:
	bin/gamesrv gamesrv101

dbsrv:
	bin/globalsrv dbsrv301 -d

centersrv:
	bin/globalsrv centersrv -d

start:
	bin/srvstartall
stop:
	bin/srvstopall
list:
	bin/srvlist
test:
	bin/pbclient login.login
